// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentSystem.dataaccsess;

#nullable disable

namespace StudentSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306001807_studentsystem")]
    partial class studentsystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoursesStudents", b =>
                {
                    b.Property<int>("CoursesCourseid")
                        .HasColumnType("int");

                    b.Property<int>("StudentsStudentId")
                        .HasColumnType("int");

                    b.HasKey("CoursesCourseid", "StudentsStudentId");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("CoursesStudents");
                });

            modelBuilder.Entity("StudentSystem.Models.Courses", b =>
                {
                    b.Property<int>("Courseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Courseid"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("endtDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Courseid");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("StudentSystem.Models.HomeWorkSubmissions", b =>
                {
                    b.Property<int>("HomeWorkid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeWorkid"));

                    b.Property<int>("Contentype")
                        .HasColumnType("int");

                    b.Property<int?>("CoursesCourseid")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("StudentsStudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("content")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("courseid")
                        .HasColumnType("int");

                    b.HasKey("HomeWorkid");

                    b.HasIndex("CoursesCourseid");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("HomeWorkSubmissions");
                });

            modelBuilder.Entity("StudentSystem.Models.Recources", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CoursesCourseid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("URL")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("resourceType")
                        .HasColumnType("int");

                    b.HasKey("ResourceId");

                    b.HasIndex("CoursesCourseid");

                    b.ToTable("Recources");
                });

            modelBuilder.Entity("StudentSystem.Models.StudentCourses", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("CoursesCourseid")
                        .HasColumnType("int");

                    b.Property<int?>("StudentsStudentId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CoursesCourseid");

                    b.HasIndex("StudentsStudentId");

                    b.ToTable("StudentCourses");
                });

            modelBuilder.Entity("StudentSystem.Models.Students", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("RegisteredOn")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoursesStudents", b =>
                {
                    b.HasOne("StudentSystem.Models.Courses", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentSystem.Models.Students", null)
                        .WithMany()
                        .HasForeignKey("StudentsStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentSystem.Models.HomeWorkSubmissions", b =>
                {
                    b.HasOne("StudentSystem.Models.Courses", "Courses")
                        .WithMany("HomeWorkSubmissions")
                        .HasForeignKey("CoursesCourseid");

                    b.HasOne("StudentSystem.Models.Students", "Students")
                        .WithMany("HomeWorkSubmissions")
                        .HasForeignKey("StudentsStudentId");

                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentSystem.Models.Recources", b =>
                {
                    b.HasOne("StudentSystem.Models.Courses", "Courses")
                        .WithMany("Recources")
                        .HasForeignKey("CoursesCourseid");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("StudentSystem.Models.StudentCourses", b =>
                {
                    b.HasOne("StudentSystem.Models.Courses", "Courses")
                        .WithMany()
                        .HasForeignKey("CoursesCourseid");

                    b.HasOne("StudentSystem.Models.Students", "Students")
                        .WithMany()
                        .HasForeignKey("StudentsStudentId");

                    b.Navigation("Courses");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentSystem.Models.Courses", b =>
                {
                    b.Navigation("HomeWorkSubmissions");

                    b.Navigation("Recources");
                });

            modelBuilder.Entity("StudentSystem.Models.Students", b =>
                {
                    b.Navigation("HomeWorkSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
